// Generated by gencpp from file custom_msgs/ChatPrompt.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_CHATPROMPT_H
#define CUSTOM_MSGS_MESSAGE_CHATPROMPT_H

#include <ros/service_traits.h>


#include <custom_msgs/ChatPromptRequest.h>
#include <custom_msgs/ChatPromptResponse.h>


namespace custom_msgs
{

struct ChatPrompt
{

typedef ChatPromptRequest Request;
typedef ChatPromptResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChatPrompt
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::ChatPrompt > {
  static const char* value()
  {
    return "e0e4e53d8b56a3ee57408d4081b2c754";
  }

  static const char* value(const ::custom_msgs::ChatPrompt&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::ChatPrompt > {
  static const char* value()
  {
    return "custom_msgs/ChatPrompt";
  }

  static const char* value(const ::custom_msgs::ChatPrompt&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::ChatPromptRequest> should match
// service_traits::MD5Sum< ::custom_msgs::ChatPrompt >
template<>
struct MD5Sum< ::custom_msgs::ChatPromptRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::ChatPrompt >::value();
  }
  static const char* value(const ::custom_msgs::ChatPromptRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::ChatPromptRequest> should match
// service_traits::DataType< ::custom_msgs::ChatPrompt >
template<>
struct DataType< ::custom_msgs::ChatPromptRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::ChatPrompt >::value();
  }
  static const char* value(const ::custom_msgs::ChatPromptRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::ChatPromptResponse> should match
// service_traits::MD5Sum< ::custom_msgs::ChatPrompt >
template<>
struct MD5Sum< ::custom_msgs::ChatPromptResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::ChatPrompt >::value();
  }
  static const char* value(const ::custom_msgs::ChatPromptResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::ChatPromptResponse> should match
// service_traits::DataType< ::custom_msgs::ChatPrompt >
template<>
struct DataType< ::custom_msgs::ChatPromptResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::ChatPrompt >::value();
  }
  static const char* value(const ::custom_msgs::ChatPromptResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_CHATPROMPT_H
